[project]
name = "project"
version = "0.1.0"
description = ""
mainfile = "__init__.py"
requires-python = ">=3.10"

[project.metadata]
authors = []
maintainers = []
readme = "README.md"
license = ""
license_file = ""
keywords = []
classifiers = []
copyright = ""

[project.urls]
changelog = ""
homepage = ""
documentation = ""

[project.dependencies]
Django = "==3.2.16"
asgiref = "==3.4.1"
autopep8 = "==1.6.0"
dj-database-url = "==0.5.0"
gunicorn = "==20.1.0"
pycodestyle = "==2.8.0"
pytz = "==2021.3"
sqlparse = "==0.4.2"
toml = "==0.10.2"
whitenoise = "==5.3.0"
django-environ = "==0.8.1"

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = []
includes = []
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []

[venv.envprj]
env_dir = ".venv/envprj"
env_name = "envprj"
env_exe = ".venv/envprj/Scripts/python.exe"
bin_path = ".venv/envprj/Scripts"
version = "3.10.6"
default = false

[venv.toup]
env_dir = ".venv/toup"
env_name = "toup"
env_exe = ".venv/toup/Scripts/python.exe"
bin_path = ".venv/toup/Scripts"
version = "3.10.6"
default = true

